export const CACHE_TIME = 3600000; // 1 hour

// COMPETITIONS
export const ALL_COMPETITIONS = 'GET_ALL_COMPETITIONS';
export const COMPETITION_BY_ID = 'GET_COMPETITION_BY_ID';
export const COMPETITION_ROUNDS = 'GET_COMPETITION_ROUNDS';

// JUDGES
export const JUDGES_BY_EFFECTIVENESS = 'JUDGES_BY_EFFECTIVENESS';
export const MOST_VOTING_JUDGE_COMPETITION = 'MOST_VOTING_JUDGE_COMPETITION';
export const MOST_VOTING_JUDGE_GLOBAL = 'MOST_VOTING_JUDGE_GLOBAL';

// MATCHES
export const MATCHES_BY_DIFFERENCE_COMPETITION = 'MATCHES_BY_DIFFERENCE_COMPETITION';
export const MATCHES_BY_DIFFERENCE_GLOBAL = 'MATCHES_BY_DIFFERENCE_GLOBAL';
export const MATCHES_BY_POINTS_COMPETITION = 'MATCHES_BY_POINTS_COMPETITION';
export const MATCHES_BY_POINTS_GLOBAL = 'MATCHES_BY_POINTS_GLOBAL';
export const MATCH_HOME_PARTICIPANT = 'MATCH_HOME_PARTICIPANT';
export const MATCH_AWAY_PARTICIPANT = 'MATCH_AWAY_PARTICIPANT';
export const MATCH_WINNER_PARTICIPANT = 'MATCH_WINNER_PARTICIPANT';
export const MATCH_LOSER_PARTICIPANT = 'MATCH_LOSER_PARTICIPANT';
export const MATCH_THEMATICS = 'MATCH_THEMATICS';
export const MATCH_WORDS = 'MATCH_WORDS';
export const MATCH_VOTES = 'MATCH_VOTES';
export const MATCH_PLAYED_COMPETITION = 'MATCH_PLAYED_COMPETITION';
export const MATCH_PLAYED_GLOBAL = 'MATCH_PLAYED_GLOBAL';
export const MATCH_BY_TYPE_COMPETITION = 'MATCH_BY_TYPE_COMPETITION';
export const MATCH_BY_TYPE_GLOBAL = 'MATCH_BY_TYPE_GLOBAL';
export const MATCH_HOME_POINTS = 'MATCH_HOME_POINTS';
export const MATCH_AWAY_POINTS = 'MATCH_AWAY_POINTS';

// PARTICIPANTS
export const ALL_PARTICIPANTS = 'ALL_PARTICIPANTS';
export const PARTICIPANT_BY_ID = 'PARTICIPANT_BY_ID';

// POSITIONS
export const POSITIONS_COMPETITION = 'POSITIONS_COMPETITION';
export const POSITIONS_GLOBAL = 'POSITIONS_GLOBAL';
export const POSITION_AVG = 'POSITION_AVG';

// ROUNDS
export const ROUND_MATCHES = 'ROUND_MATCHES';

// VOTES
export const VOTE_JUDGE = 'VOTE_JUDGE';
export const VOTE_WINNER = 'VOTE_WINNER';
export const VOTE_LOSER = 'VOTE_LOSER';

// WORDS
export const MOST_USED_WORDS_GLOBAL = 'MOST_USED_WORDS_GLOBAL';